#!/bin/sh

# docker-machine create --driver virtualbox --engine-insecure-registry localhost:5000 default

if [ ! -f certs/domain.key ]; then
    mkdir -p auth certs data

    openssl req -new > certs/domain.csr
    mv privkey.pem certs
    openssl rsa -in certs/privkey.pem -out certs/key.pem
    openssl x509 -in certs/domain.csr -out certs/domain.pem -req -signkey certs/key.pem -days 1001
    cat certs/key.pem >> certs/domain.pem

fi

docker run -d -p 5000:5000 \
    --restart=always \
    --name registry \
    -v `pwd`/data:/var/lib/registry \
    -v `pwd`/certs:/certs \
    -e REGISTRY_HTTP_TLS_CERTIFICATE=/certs/domain.crt \
    -e REGISTRY_HTTP_TLS_KEY=/certs/domain.key \
registry:2

if [ ! -f auth/htpasswd ]; then
    docker run --entrypoint htpasswd registry:2 -Bbn routematch routepass  > auth/htpasswd
fi

sleep 5
docker kill `docker ps| grep registry| awk '{ print $1 }'`
docker rm `docker ps| grep registry| awk '{ print $1 }'`

docker run -d -p 5000:5000 \
    --restart=always \
    --name registry \
    -v `pwd`/data:/var/lib/registry \
    -v `pwd`/certs:/certs \
    -v `pwd`/auth:/auth \
    -e REGISTRY_HTTP_TLS_CERTIFICATE=/certs/domain.crt \
    -e REGISTRY_HTTP_TLS_KEY=/certs/domain.key \
    -e "REGISTRY_AUTH=htpasswd" \
    -e "REGISTRY_AUTH_HTPASSWD_REALM=Registry Realm" \
    -e REGISTRY_AUTH_HTPASSWD_PATH=/auth/htpasswd \
registry:2

docker login localhost:5000
